# Project specific constants
MIN_TASK_DURATION_HOURS = 4
NON_PREFERENCE_TIME_ADJUSTMENT_HOURS = 1
AVERAGE_GAME_TIME_IN_MINUTES = 110
MORNING_SHIFT_START_TIME = "10:00"
NIGHT_SHIFT_START_TIME = "18:00"
SHIFT_DURATION_IN_HOURS = 8
MAX_TASKS_PER_EMPLOYEE = 4

# Time based helper constants
SECONDS_IN_ONE_HOUR = 60 * 60
